// Interactive tutorial lessons. S = counters collected since the lesson started.
import { tr } from '../ui/i18n.js';

export const LESSONS = [
  { id: 'move', dummy: 'stand', title: () => tr('Movement', 'การเคลื่อนไหว'),
    text: () => tr('Walk forward / backward (← →) and dash by tapping → twice. Tap ↑ or ↓ to sidestep.', 'เดินหน้า/ถอยหลัง (← →) แตะ → สองครั้งเพื่อแดช และแตะ ↑ หรือ ↓ เพื่อสเต็ปหลบข้าง'),
    goal: 3, check: (S) => Math.min(3, (S.walkF ? 1 : 0) + (S.dash ? 1 : 0) + (S.ss ? 1 : 0)) },
  { id: 'attack', dummy: 'stand', title: () => tr('Four-button attacks', 'โจมตีสี่ปุ่ม'),
    text: () => tr('1 = left punch, 2 = right punch, 3 = left kick, 4 = right kick. Use each button once.', '1 = หมัดซ้าย 2 = หมัดขวา 3 = เตะซ้าย 4 = เตะขวา กดแต่ละปุ่มอย่างละครั้ง'),
    goal: 4, check: (S) => S.btns.size },
  { id: 'string', dummy: 'stand', title: () => tr('Strings', 'คอมโบต่อเนื่อง'),
    text: () => tr('Strings are button chains. Press 1, then 2, then 3 in rhythm (1,2,3) and land all three hits on the dummy.', 'สตริงคือการกดปุ่มต่อเนื่อง กด 1 แล้ว 2 แล้ว 3 ตามจังหวะ (1,2,3) ให้ติดครบทั้งสามฮิต'),
    goal: 3, check: (S) => Math.min(3, S.maxCombo) },
  { id: 'guard', dummy: 'cpu1', title: () => tr('Blocking', 'การป้องกัน'),
    text: () => tr('Hold BACK to block. Hold DOWN+BACK to crouch-block low attacks. Block 4 attacks.', 'กด "ถอยหลัง" เพื่อบล็อก กด ↙ เพื่อบล็อกท่าล่าง บล็อกให้ได้ 4 ครั้ง'),
    goal: 4, check: (S) => S.blocks },
  { id: 'levels', dummy: 'stand', title: () => tr('High / Mid / Low', 'ท่าบน / กลาง / ล่าง'),
    text: () => tr('High attacks whiff on a crouching foe; lows must be blocked crouching; mids beat crouch-blocking. Land a low (d+1) and a mid (d/f+1).', 'ท่าบนพลาดถ้าคู่ต่อสู้ย่อ ท่าล่างต้องบล็อกแบบย่อ ท่ากลางทะลวงการย่อบล็อก ลองใช้ d+1 (ล่าง) และ d/f+1 (กลาง)'),
    goal: 2, check: (S) => (S.lowHit ? 1 : 0) + (S.midHit ? 1 : 0) },
  { id: 'throw', dummy: 'stand', title: () => tr('Throws', 'จับทุ่ม'),
    text: () => tr('Press 1+3 or 2+4 to throw. Throws beat blocking but can be ducked!', 'กด 1+3 หรือ 2+4 เพื่อจับทุ่ม จับทุ่มชนะการบล็อก แต่ย่อหลบได้!'),
    goal: 1, check: (S) => S.grabs },
  { id: 'break', dummy: 'throwme', title: () => tr('Throw break', 'สลัดหลุดจากการจับ'),
    text: () => tr('The dummy will try to throw you. Press 1 (for 1+3 throws) or 2 (for 2+4 throws) right after being grabbed to break it.', 'หุ่นจะพยายามจับคุณ กด 1 (ท่า 1+3) หรือ 2 (ท่า 2+4) หลังโดนจับเพื่อสลัดหลุด'),
    goal: 1, check: (S) => S.breaks },
  { id: 'juggle', dummy: 'stand', title: () => tr('Launch & juggle', 'ลอยตัวและตามคอมโบ'),
    text: () => tr('Launch the dummy with d/f+2 (or ws+4), then hit it while airborne. Get a 4+ hit combo.', 'ส่งหุ่นลอยด้วย d/f+2 (หรือ ws+4) แล้วต่อคอมโบขณะลอย ให้ได้ 4 ฮิตขึ้นไป'),
    goal: 4, check: (S) => Math.min(4, S.maxCombo) },
  { id: 'wall', dummy: 'stand', title: () => tr('Walls', 'กำแพง'),
    text: () => tr('Push the dummy to the wall and use a power move (f+2 or similar) to wall splat it, then keep the combo going.', 'ดันหุ่นไปติดกำแพงแล้วใช้ท่าแรงๆ (เช่น f+2) ให้ติดกำแพง แล้วต่อคอมโบต่อ'),
    goal: 1, check: (S) => S.walls, wallPractice: true },
  { id: 'heat', dummy: 'stand', title: () => tr('Heat', 'ฮีท'),
    text: () => tr('Press 2+3 to Heat Burst. In Heat you deal chip damage and can cancel with Heat Dash (→→ after a hit). Press 2+3 again for a Heat Smash!', 'กด 2+3 เพื่อ Heat Burst ในสถานะฮีทการโจมตีสร้างดาเมจแม้ถูกบล็อก และใช้ Heat Dash ได้ (→→ หลังโดน) กด 2+3 อีกครั้งเพื่อ Heat Smash!'),
    goal: 2, check: (S) => (S.heatburst ? 1 : 0) + (S.heatsmash ? 1 : 0) },
  { id: 'rage', dummy: 'stand', title: () => tr('Rage', 'เรจ'),
    text: () => tr('At low health you enter Rage. Press 1+2 for a Rage Art - a huge cinematic attack.', 'เมื่อพลังชีวิตต่ำคุณจะเข้าสู่ Rage กด 1+2 เพื่อใช้ Rage Art ท่าไม้ตายที่ทรงพลัง'),
    goal: 1, check: (S) => S.rageart, lowHp: true },
  { id: 'punish', dummy: 'cpu2', title: () => tr('Punishing', 'ลงโทษความผิดพลาด'),
    text: () => tr('Block an attack with a big recovery, then punish with a fast launcher. Watch the frame data panel!', 'บล็อกท่าที่ช่องว่างเยอะ แล้วตอบโต้ด้วยท่าเร็วที่ส่งลอย ดูตารางเฟรมดาต้าด้านล่างประกอบ'),
    goal: 1, check: (S) => S.punish },
];
